### PR TITLE
Change `seed` to `rng` for `unwrap_phase` function

### PR DESCRIPTION
**Pull request by PinkShnack**
Solves #14.

I noticed that the following test fails because it tries to write to the hdf5 file and produces a `KeyError` rather than the other errors listed. 

`tests.test_series.py::test_series_meta`

### CODE REVIEW

**Comment by PinkShnack** [comment]
Of course, this `rng` argument only works for skimage over a certain version... So the tests here fail.

So either we live with the deprecation warning and pin `skimage==0.22` or we restrict `qpimage` to later python and therefore skimage versions...

**Comment by PinkShnack** [comment]
> Of course, this `rng` argument only works for skimage over a certain version... So the tests here fail.
> 
> So either we live with the deprecation warning and pin `skimage==0.22` or we restrict `qpimage` to later python and therefore skimage versions...

### Solution?

Looks like skimage==0.21.0 is when seed started being deprecated, and that is `requires-python = '>=3.8'`. We could just match that for qpimage?

**Comment by PinkShnack** [comment]
Second point is the failing py3.8 build:

I noticed that the following test fails because it tries to write to the hdf5 file and produces a KeyError rather than the other errors listed. `tests.test_series.py::test_series_meta`. I can fix add the keyerror, but wasn't sure if this is the core problem.

**Comment by PinkShnack** [comment]
> Yes, dropping Python<3.8 sounds reasonable. Could you please also update the github workflows? I think it is fine to always test only against the latest stable release of python (if that is possible).

I can try!

**Comment by paulmueller** [comment]
> > Yes, dropping Python<3.8 sounds reasonable. Could you please also update the github workflows? I think it is fine to always test only against the latest stable release of python (if that is possible).
> 
> I can try!

Otherwise just test and deploy with Python 3.11.

**Comment by PinkShnack** [comment]
We have 

```yml
on:
  push:
  pull_request:
```

which duplicates the jobs. Any reason to have both? We could just have push.

**Comment by PinkShnack** [comment]
> > > Yes, dropping Python<3.8 sounds reasonable. Could you please also update the github workflows? I think it is fine to always test only against the latest stable release of python (if that is possible).
> > 
> > 
> > I can try!
> 
> Otherwise just test and deploy with Python 3.11.

Yeah you can use

```yml
      with:
        python-version: '3.x'
```
apparently :)

**Comment by paulmueller** [comment]
> We have
> 
> ```yaml
> on:
>   push:
>   pull_request:
> ```
> 
> which duplicates the jobs. Any reason to have both? We could just have push.

What about pull requests from a fork?

**Comment by PinkShnack** [comment]
> > We have
> > ```
> > on:
> >   push:
> >   pull_request:
> > ```
> > 
> > 
> > which duplicates the jobs. Any reason to have both? We could just have push.
> 
> What about pull requests from a fork?

Yeah, not sure whether push covers forks. Only one way to check!

**Review by paulmueller — APPROVED** [review]

**Pull request merged**
